config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  resources :items do
    resources :orders,only: [:index, :create]
    get '/likes',to: 'likes#create'
    delete '/likes',to: 'likes#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '北海道' }, { id: 2, name: '青森県' }, { id: 3, name: '岩手県' },
    { id: 4, name: '宮城県' }, { id: 5, name: '秋田県' }, { id: 6, name: '山形県' },
    { id: 7, name: '福島県' }, { id: 8, name: '茨城県' }, { id: 9, name: '栃木県' },
    { id: 10, name: '群馬県' }, { id: 11, name: '埼玉県' }, { id: 12, name: '千葉県' },
    { id: 13, name: '東京都' }, { id: 14, name: '神奈川県' }, { id: 15, name: '新潟県' },
    { id: 16, name: '富山県' }, { id: 17, name: '石川県' }, { id: 18, name: '福井県' },
    { id: 19, name: '山梨県' }, { id: 20, name: '長野県' }, { id: 21, name: '岐阜県' },
    { id: 22, name: '静岡県' }, { id: 23, name: '愛知県' }, { id: 24, name: '三重県' },
    { id: 25, name: '滋賀県' }, { id: 26, name: '京都府' }, { id: 27, name: '大阪府' },
    { id: 28, name: '兵庫県' }, { id: 29, name: '奈良県' }, { id: 30, name: '和歌山県' },
    { id: 31, name: '鳥取県' }, { id: 32, name: '島根県' }, { id: 33, name: '岡山県' },
    { id: 34, name: '広島県' }, { id: 35, name: '山口県' }, { id: 36, name: '徳島県' },
    { id: 37, name: '香川県' }, { id: 38, name: '愛媛県' }, { id: 39, name: '高知県' },
    { id: 40, name: '福岡県' }, { id: 41, name: '佐賀県' }, { id: 42, name: '長崎県' },
    { id: 43, name: '熊本県' }, { id: 44, name: '大分県' }, { id: 45, name: '宮崎県' },
    { id: 46, name: '鹿児島県' }, { id: 47, name: '沖縄県' }
  ]
end

app/models/area_day.rb
class AreaDay < ActiveHash::Base
  self.data = [
    { id: 0, day: '---' },
    { id: 1, day: '1-2日で発送' },
    { id: 2, day: '2-3日で発送' },
    { id: 3, day: '4-7日で発送' }
  ]
end

app/models/burden.rb
class Burden < ActiveHash::Base
  self.data = [
    { id: 0, fee: '---' },
    { id: 1, fee: '着払い(購入者負担)' },
    { id: 2, fee: '送料込み(出品者負担)' }
  ]
end

app/models/buy.rb
class Buy < ApplicationRecord
  attr_accessor :token
  belongs_to :order
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '5000円までの商品' },
    { id: 2, name: '10000円までの商品' },
    { id: 3, name: '20000円までの商品' },
    { id: 4, name: '30000円までの商品' },
  ]
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :burden
  belongs_to_active_hash :area
  belongs_to_active_hash :area_day

  has_one_attached :image
  belongs_to :user
  has_one :order
  has_many :likes, dependent: :destroy

  validates :product, :product_copy, :category_id, :item_pas, presence: true
  validates :burden_id, :area_id, :area_day_id, :price, :image, presence: true

  validates :category_id, :burden_id, :area_id, :area_day_id, presence: true, numericality: { other_than: 0 } 
  validates :price, inclusion: { in: 1000..35000 }

  def like_user(user_id)
    likes.find_by(user_id: user_id)
   end
end

app/models/lile.rb
class Lile < ApplicationRecord
  belongs_to :item
  belongs_to :user

  validates_uniqueness_of :item_id, scope: :user_id
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :item
  belongs_to :user
  has_one :buy
end

app/models/order_buy.rb
class OrderBuy
  include ActiveModel::Model
  attr_accessor :postal_code, :area_id, :city, :address, :building,:tel, :user_id, :item_id, :order_id, :token

  with_options presence: true do
    validates :area_id,numericality: { other_than: 0 }
    validates :postal_code, format: { with: /\A\d{3}[-]\d{4}\z/}
    validates :city
    validates :address
    validates :tel, format: { with: /\A\d{11}\z/}
    validates :token
  end


def save
  order = Order.create(user_id: user_id, item_id: item_id)
  Buy.create( postal_code: postal_code, area_id: area_id, city: city, address: address, building: building,tel: tel, order_id: order.id)
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         with_options presence: true do
          validates :nickname
          validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i}
          validates :first_name, format: { with: /\A[ぁ-んァ-ン一-龥]/}
          validates :last_name, format: { with: /\A[ぁ-んァ-ン一-龥]/}
          validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/}
          validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/}
          validates :birthday
          end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :first_name, :last_name, :first_name_kana,:last_name_kana,:birthday])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!,except:[:index,:show]
  before_action :set_item, only: [:edit, :show, :update, :destroy]

  def index
    @items = Item.all.order("created_at DESC")
  end
  
  def index2
    @items = Item.where(category.id)
  end


  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

    def show
    end

    def edit
      unless @item.user.id == current_user.id
        redirect_to action: :index
      end
    end

    def update
      if @item.update(item_params)
         redirect_to item_path
      else
         render :edit
      end
    end

    def destroy
        @item.destroy if @item.user.id == current_user.id
          redirect_to root_path
    end

  private

  def item_params
    params.require(:item).permit(:product, :product_copy, :price, :category_id, :burden_id, :area_id, :area_day_id, :item_pas, :image).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post, only: [:create, :destroy]

  def create
    @like = Lile.create(user_id: current_user.id, item_id: params[:item_id])
  end

  

  def destroy
    like = Lile.find_by(user_id: current_user.id, item_id: params[:item_id])
    like.destroy
  end

  private

  def set_post
    @item = Item.find(params[:item_id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!,only: [:index, :create]
  before_action :set_item, only: [:index,:create]

  def index
    @order = OrderBuy.new
    if @item.user.id == current_user.id || @item.order.present?
      redirect_to root_path
    end
  end

  def create
    @order = OrderBuy.new(buy_params)
    if @order.valid?
    pay_item
    @order.save
    redirect_to root_path
    else
      render :index
    end
  end

  private

  def buy_params
    params.permit( :token, :postal_code, :area_id, :city, :address, :building,:tel,:item_id).merge( user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:item_id])
  end

  def pay_item

    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    Payjp::Charge.create(
      amount: @item.price,
      card: buy_params[:token],
      currency:'jpy'
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/items/edit.html.erb
<%# cssは商品出品のものを併用しています。
app/assets/stylesheets/items/new.css %>

<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('IWAI logo.jpg' , size: '185x50'), "/" %>
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item,local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        出品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :hoge, id:"item-image" %>
      </div>
    </div>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        ▶︎ 商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :product, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          ▶︎ 商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :product_copy, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">▶︎ 商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 配送について %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>▶︎ 配送について</span>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:burden_id, Burden.all, :id, :fee, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:area_day_id, AreaDay.all, :id, :day, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>
    <%# /配送について %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>▶︎ 販売価格<br>(¥300〜9,999,999)</span>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
          </span>
        </div>
      </div>
    </div>
    <%# /販売価格 %>
      <div class="weight-bold-text">
        ▶︎ 出品パスワード
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :item_pas, class:"items-text", id:"item-name", placeholder:"出品用パスワードを入力して下さい", maxlength:"10" %>
    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', "#", class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">iwai利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('IWAI logo2.jpg' , size: '185x50'), "/" %>
  </footer>
</div>

app/views/items/index.html.erb
<!doctype html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="description" content="最新技術と自然との調和を目指す">
<meta name="viewport" content="width=device-width">
<title>IWAI | 出会ったことのないお祝いを届ける</title>
<%# <link rel="stylesheet" media="all" href="app/assets/stylesheets/css/style.css"> %>
<%# <script src="javascript/script.js"></script> %>

</head>

<body id="top">
<header id="header">
	<div id="headerWrap">
		<h1><%= image_tag "IWAI logo.jpg", :width=>"142", :height=>"80", :alt=>"logo"%></h1>
		<nav id="mainnav">
			<p id="menuWrap"><a id="menu"><span id="menuBtn"></span></a></p>
			<div class="panel">
				<ul>
					<li><a href="#top">TOP</a></li>
					<li><a href="#sec01">MESSAGE</a></li>
					<li><a href="#sec06">CATEGORY</a></li>
					<li><a href="#sec03">NEW ITEM</a></li>
					<li><a href="#sec04">CREATOR</a></li>
      <% if user_signed_in? %>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout"%> </li>
			<li><%= link_to "#{current_user.nickname}さんログイン中", "#", class: "user-nickname"%> </li>
      <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
				</ul>
			</div>
		</nav>
	</div>
</header>

<div id="mainImg">
	<%= image_tag "IWAI top.jpg" %>
</div>

<!-- MESSAGE -->
<section id="sec01">
	<header>
		<h2><span>Message</span></h2>
	</header>
	<div class="innerS">
		親友や友人、会社の同僚に先輩後輩、結婚という新しい門出に"あなたが選んだ価値あるプレゼント"を贈りましょう。
		『IWIA』では様々なクリエイターが創った、ここでしか出会えない商品を購入することができます。
		いたる所で見かける商品ではなく、『目新しい』『斬新な発想』『センスある一品』だからこそ相手の記憶に残ります。
	</div>
</section>
<!-- // MESSAGE -->
<%= image_tag "3sen.jpg" %>
<!-- CATEGORY -->
<section id="sec06">
	<header>
		<h2><span>CATEGORY</span></h2>
			<div class="innerS">
	大切な方に贈る商品を5000円、10000円、20000円、300000円、と予算別に一覧表示をさせて選びやすくすることができます。
	</div>
	</header>
	<ul id="gallery">
		<li><%= link_to image_tag(' 5000.jpg' , size: '426x418'), "/" %></li>
		<li><%= link_to image_tag(' 10000.jpg' , size: '426x418'), "/" %></li>
		<li><%= link_to image_tag(' 20000.jpg' , size: '426x418'), "/" %></li>
		<li><%= link_to image_tag(' 30000.jpg' , size: '426x418'), "/" %></li>
	</ul>
</section>
<!-- // CATEGORY -->

<!-- NEW ITEM -->
<section id="sec03">
	<header>
		<h2><span>NEW ITEM</span></h2>
	</header>
	<div class="innerS">
		<%= image_tag "newitem.jpg", :width=>"726", :height=>"333", :alt=>""%>
		<p>世界中のクリエイター達が創りあげた新商品が随時更新されます。最新アイテムをチェックしてプレゼントを届けましょう。</p>
	</div>
</section>

<!-- // NEW ITEM -->
   <ul class='item-lists'>
      <% @items.each do |item| %> 
      <li class='list'>
        <%= link_to item_path(item.id) do %>
        <div class='item-img-content'>
          <%= image_tag item.image, class: "item-img" %>
 					<div id="likes_buttons<%= item.id %>">
  					 <%= render partial: 'likes/like', locals: { item: item, like: @like} %>
 					</div>
					 <p>いいね</p>
					
           <% if item.order != nil %>
          <div class='sold-out'>
              <span>売り切れ!!</span>
          </div>
           <% end %>

        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.product %>
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円<br>(税込み)</span>
            <div class='star-btn'>
            </div>
          </div>
        </div>
        <% end %>
      <% end %>
      </li>
		</ul>

<%= image_tag "aida.jpg" %>
<!-- CREATOR --> 
<section id="sec04">
	<header>
		<h2><span>CREATOR</span></h2>
	</header>
	<div class="inner">
		<ul class="col3">
			<li>
				<p class="img"><%= link_to image_tag "create3.jpg", :width=>"270", :height=>"206", :alt=>"" %></p>
				<p><b>クリエイター 【 Yudai 】</b></p>
				<p>彼は独創的なセンスで様々なアート作品を作り出している。彼は独創的なセンスで様々なアート作品を作り出している。彼は独創的なセンスで様々なアート作品を作り出している。</p>
			</li>
			<li>
				<p class="img"><%= link_to image_tag "create2.jpg", :width=>"270", :height=>"206", :alt=>"" %></p>
				<p><b>クリエイター 【 鯛子 】</b></p>
				<p>男女でものづくりを行う感性がたくさんの人々を魅了する。男女でものづくりを行う感性がたくさんの人々を魅了する。男女でものづくりを行う感性がたくさんの人々を魅了する。</p>
			</li>
			<li>
				<p class="img"><%= link_to image_tag "create1.jpg", :width=>"270", :height=>"206", :alt=>"" %></p>
				<p><b>クリエイター 【 MEKATA 】</b></p>
				<p>8bitの世界観でどこか懐かしいレトロ感がある商品を発信するITBOY。8bitの世界観でどこか懐かしいレトロ感がある商品を発信するITBOY。8bitの世界観でどこか懐かしいレトロ感がある商品を発信するITBOY。</p>
			</li>
		</ul>
	</div>
</section>
<!-- // CREATOR -->
<%= link_to new_item_path do %>　
<div class='purchase-btn'>
  <span class='purchase-btn-text'>出品</span>
    <%= image_tag 'mizuhiki.png' , size: '185x50' ,class: "purchase-btn-icon" %>
  <% end %>
</div>

<footer id="footer">
	Copyright(c) 2020 IWAI Inc. All Rights Reserved. Design by Yudai Mekata
</footer>

</body>
</html>

app/views/items/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.product %>
    </h2>
    <div class='item-img-content'>
      <%= image_tag @item.image ,class:"item-box-img" %>
      <%# 商品が売れている場合は、sold outを表示しましょう %>
    <% if @item.order != nil %>
      <div class='sold-out'>
        <span>売り切れ!!</span>
      </div>
    <% end %>
      <%# //商品が売れている場合は、sold outを表示しましょう %>
    </div>
    <div class="item-price-box">
      <span class="item-price">
        ¥ <%= @item.price%>
      </span>
      <span class="item-postage">
        (税込) 送料込み
      </span>
    </div>
 					<div id="likes_buttons<%= @item.id %>">
  					 <%= render partial: 'likes/like', locals: { item: @item, like: @like} %>
             いいね
 					</div>
    <%# ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>
  <% if  @item.order == nil  %>
  <% if user_signed_in? && current_user.id == @item.user_id %>
    <%= link_to '商品の編集', edit_item_path(@item.id), method: :get, class: "item-red-btn" %>
    <p class='or-text'>or</p>
    <%= link_to '削除', item_path, method: :delete, class:'item-destroy' %>
  <% elsif user_signed_in? && current_user.id != @item.user_id %>
    <%# 商品が売れていない場合はこちらを表示しましょう %>
    <%= link_to '購入画面に進む', item_orders_path(item_id: @item.id) ,class:"item-red-btn"%>
    <% end %>
    <%# //商品が売れていない場合はこちらを表示しましょう %>
  <% end %>

    <%# //ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>

    <div class="item-explain-box">
      <span><%= @item.product_copy %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @item.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @item.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= @item.burden.fee %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= @item.area.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= @item.area_day.day %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
    </div>
  </div>
  <%# /商品の概要 %>

  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>
  <a href="#" class='another-item'><%= @item.category.name %>をもっと見る</a>
</div>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Iwai</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<% if user_signed_in? %>

  <% if Lile.exists?(item_id:item.id,user_id:current_user.id) %>
    <%= link_to item_likes_path(item_id: item.id), method: :delete, remote: true do %>
      <div class="vertical_like">
       <%= image_tag "lile_red.png", size: '40x40' %>
      </div>
    <% end %>
  <% else %>
    <%= link_to item_likes_path(item.id), method: :get, remote: true do %>
      <div class="vertical_like">
        <%= image_tag "like.png", size: '40x40' %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$('#likes_buttons<%= @item.id %>').html("<%= j(render partial: 'likes/like', locals: {item: @item}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons<%= @item.id %>').html("<%= j(render partial: 'likes/like', locals: {item: @item}) %>");

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    IWAIを使って大切な人へお祝いをしよう
  </p>
  <h2 class='ad-footer-title'>
    スマホアプリでさらに利用が簡単！
  </h2>
  <div class='store-btn'>
  </div>
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>IWAIについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'IWAI利用規約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>IWAIを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>IWAIについて</h2>
      <ul>
        <li><%= link_to 'IWAIガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'IWAIロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("IWAI logo2.jpg", class:"logo-white"), "#" %>
  <p>© IWAI</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("IWAI logo.jpg", class:"furima-icon"), "/" %>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから探す'>
      <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    </form>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
    </ul>
    <ul class='lists-right'>
      <%# deviseを導入できたら、ログインの有無で表示が変わるように分岐しましょう%>
      <% if user_signed_in? %>
      <li><%= link_to "#{current_user.nickname}さんログイン中", "#", class: "user-nickname"%> </li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout"%> </li>
      <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
      <%# //deviseを導入できたら、ログインの有無で表示が変わるように分岐しましょう%>
    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>IWAI利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("IWAI logo.jpg", class:"second-logo"), "/" %>
</header>